#ifndef MESH_PARAMETERS_H
#define MESH_PARAMETERS_H

#include <parameters.h>
#include <types.h>
#include <string>

// DO NOT MODIFY - This file is automatically generated during compilation.

class MeshParameters : public Parameters {
  public:
    MeshParameters() : Parameters(2){
      mDomainMinX = 0.0;
      mDomainMaxX = 1.0;
      mDomainMinY = 0.0;
      mDomainMaxY = 1.0;
      mGridPointsX = 101;
      mGridPointsY = 101;
    }

    inline void setDomainMinX(double DomainMinX){
      mDomainMinX = DomainMinX;
    }

    inline double getDomainMinX(){
      return mDomainMinX;
    }

    inline void setDomainMaxX(double DomainMaxX){
      mDomainMaxX = DomainMaxX;
    }

    inline double getDomainMaxX(){
      return mDomainMaxX;
    }

    inline void setDomainMinY(double DomainMinY){
      mDomainMinY = DomainMinY;
    }

    inline double getDomainMinY(){
      return mDomainMinY;
    }

    inline void setDomainMaxY(double DomainMaxY){
      mDomainMaxY = DomainMaxY;
    }

    inline double getDomainMaxY(){
      return mDomainMaxY;
    }

    inline void setGridPointsX(int GridPointsX){
      mGridPointsX = GridPointsX;
    }

    inline int getGridPointsX(){
      return mGridPointsX;
    }

    inline void setGridPointsY(int GridPointsY){
      mGridPointsY = GridPointsY;
    }

    inline int getGridPointsY(){
      return mGridPointsY;
    }

    Result broadcastParameters();

  private:
    double mDomainMinX;
    double mDomainMaxX;
    double mDomainMinY;
    double mDomainMaxY;
    int mGridPointsX;
    int mGridPointsY;
};

#endif
