#include <meshparameters.h>
#include <mpicommunicator.h>

// DO NOT MODIFY - This file is automatically generated during compilation.

Result MeshParameters::broadcastParameters(){
  MPICommunicator *comm = MPICommunicator::getInstance();

  comm->broadcastParameter(&mDomainMinX);

  comm->broadcastParameter(&mDomainMaxX);

  comm->broadcastParameter(&mDomainMinY);

  comm->broadcastParameter(&mDomainMaxY);

  comm->broadcastParameter(&mGridPointsX);

  comm->broadcastParameter(&mGridPointsY);

}
