#include <waveparser.h>
#include <iostream>

using namespace std;

// DO NOT MODIFY - This file is automatically generated during compilation.

void WaveParser::updateParameters(string fname, Parameters* params){
  if(!checkId(params)){
    return;
  }
  reader.clearData();
  ParamReader::ParamResult result = reader.readFile(fname);
  if(result != ParamReader::SUCCESS){
    cout << "An error occurred while trying to read " << fname << ".\n";
    return;
  }
  WaveParameters *pars = (WaveParameters*) params;

  if(!reader.hasSection(string("Wave"))){
    return;
  }

  if(reader.hasParameter(string("Wave"),string("InitialConditions"))){
    string result = reader.readAsString(string("Wave"),string("InitialConditions"));
    if(result.compare("GAUSSIAN") == 0){
      pars->setInitialConditions(WaveParameters::GAUSSIAN);
    }
    else if(result.compare("FLAT") == 0){
      pars->setInitialConditions(WaveParameters::FLAT);
    }
    else {
      cout << "The value for parameter InitialConditions is out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("GridPointsR"))){
    int result = reader.readAsInt(string("Wave"),string("GridPointsR"));
    if(result <= 128000 && result >= 7){
      pars->setGridPointsR(result);
    }
    else{
      cout << "Parameter GridPointsR out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("GridPointsT"))){
    int result = reader.readAsInt(string("Wave"),string("GridPointsT"));
    if(result <= 128000 && result >= 7){
      pars->setGridPointsT(result);
    }
    else{
      cout << "Parameter GridPointsT out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("DomainMinR"))){
    double result = reader.readAsDouble(string("Wave"),string("DomainMinR"));
    if(result <= 1.000000e+06 && result >= -1.000000e+06){
      pars->setDomainMinR(result);
    }
    else{
      cout << "Parameter DomainMinR out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("DomainMaxR"))){
    double result = reader.readAsDouble(string("Wave"),string("DomainMaxR"));
    if(result <= 1.000000e+06 && result >= -1.000000e+06){
      pars->setDomainMaxR(result);
    }
    else{
      cout << "Parameter DomainMaxR out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("ProjectName"))){
    string result = reader.readAsString(string("Wave"),string("ProjectName"));
    if(result.compare("NULL") != 0){
      pars->setProjectName(result);
    }
    else{
      cout << "Parameter %s is not a string.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("TimeStart"))){
    double result = reader.readAsDouble(string("Wave"),string("TimeStart"));
    if(result <= 1.000000e+06 && result >= 0.000000e+00){
      pars->setTimeStart(result);
    }
    else{
      cout << "Parameter TimeStart out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("TimeEnd"))){
    double result = reader.readAsDouble(string("Wave"),string("TimeEnd"));
    if(result <= 1.000000e+06 && result >= 0.000000e+00){
      pars->setTimeEnd(result);
    }
    else{
      cout << "Parameter TimeEnd out of range.\n";
    }
  }

  if(reader.hasParameter(string("Wave"),string("GhostPoints"))){
    int result = reader.readAsInt(string("Wave"),string("GhostPoints"));
    if(result <= 10 && result >= 1){
      pars->setGhostPoints(result);
    }
    else{
      cout << "Parameter GhostPoints out of range.\n";
    }
  }

}

