#include <waveparameters.h>
#include <mpicommunicator.h>

// DO NOT MODIFY - This file is automatically generated during compilation.

Result WaveParameters::broadcastParameters(){
  MPICommunicator *comm = MPICommunicator::getInstance();

  unsigned int bcInitialConditions = static_cast<unsigned int>(mInitialConditions);
  comm->broadcastParameter(&bcInitialConditions);
  mInitialConditions = static_cast<InitialConditions>(bcInitialConditions);

  comm->broadcastParameter(&mGridPointsR);

  comm->broadcastParameter(&mGridPointsT);

  comm->broadcastParameter(&mDomainMinR);

  comm->broadcastParameter(&mDomainMaxR);

  comm->broadcastParameter(&mProjectName);

  comm->broadcastParameter(&mTimeStart);

  comm->broadcastParameter(&mTimeEnd);

  comm->broadcastParameter(&mGhostPoints);

  return SUCCESS;}
